kafka:
  mem_limit: 1024m
  cpuset: "0,1"
  image: "spotify/kafka:latest"
  hostname: kafka
  ports:
    - "9092:9092"

demo:
  mem_limit: 1024m
  cpuset: "0,1"
  image: "kafa-demo:latest"
  hostname: kafka-demo
  environment:
    DOCKER_COMPOSE: 'true'
  links:
    - kafka
  ports:
    - "12001:12001"

